# Generated by Django 5.0 on 2023-12-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_review_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
