# Generated by Django 5.0 on 2023-12-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_borrow_book_alter_borrow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='balance_after_borrow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
