# Generated by Django 5.0 on 2023-12-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userbankaccount_user_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
