# Generated by Django 5.0 on 2023-12-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userbankaccount_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
