# Generated by Django 5.0 on 2023-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='balance_after_borrow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
